version: "3.8"

services:
  postgres:
    image: postgres:16

    container_name: product_postgres

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scraper"]
      interval: 5s
      timeout: 5s
      retries: 10

    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products

    ports:
      - "5432:5432"

    volumes:
      - scraping_data:/var/lib/postgresql/data

volumes:
  scraping_data:
